name: createimage
env:
  DOCKER_REG: registry.cn-shanghai.aliyuncs.com/gen_dockerimage/gen_repository
  REG: registry.cn-shanghai.aliyuncs.com
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:
    inputs:
       Version:
        description: 'Version to input'
        required: true
        default: 'v1.0.0'
jobs:
  build:

    runs-on: ubuntu-20.04
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: login docker
      run: 
        echo "${{ secrets.PASSWORD }}" | docker login $REG --username "${{ secrets.USERNAME }}" --password-stdin
    - name: Build the Docker image
      run:
        docker build . --file src/GenGenerate.Core/Dockerfile --tag gengenerateimage
    - name: Get version
      id: get_version
      run: |
        VERSION=${{ github.event.inputs.Version }}
        [ "$VERSION" == "" ] && VERSION=release
        echo ::set-output name=VERSION::"$VERSION"
        ${{ secrets.HOST }}
    - name: push image
      run: |
        docker tag gengenerateimage $DOCKER_REG:${{ steps.get_version.outputs.version }}
        docker push $DOCKER_REG:${{ steps.get_version.outputs.version }}
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    env:
      CONTAINER_NAME: gengenerate-app
    steps:
    - name: deploy docker image
      uses: appleboy/ssh-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USERNAME }}
        password: ${{ secrets.HOST_PASSWORD }}
        port:  22
        envs: CONTAINER_NAME, DOCKER_REG, REG
        script: |
          if [ $(docker ps -a | grep -c $CONTAINER_NAME) -gt 0 ]; then docker stop $CONTAINER_NAME;docker rm $CONTAINER_NAME;fi
          echo "${{ secrets.PASSWORD }}" | docker login $REG --username "${{ secrets.USERNAME }}" --password-stdin
          docker run --name $CONTAINER_NAME -d -p 8081:80 $DOCKER_REG:${{ needs.build.outputs.version }}
